services:

    pedroteixeira.grid:
        class: PedroTeixeira\Bundle\GridBundle\Grid\Factory
        arguments: [ '@service_container' ]

    pedroteixeira.twig.grid:
        class: PedroTeixeira\Bundle\GridBundle\Twig\GridExtension
        tags:
            - { name: twig.extension }
        arguments: ['@service_container', '@twig']